ALTER SESSION SET nls_date_format = 'DD-MM-YYYY HH24:MI:SS'

-- Creo la tabla ROL
CREATE TABLE rol (
    id_rol       NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    nombre       VARCHAR(30) NOT NULL,
    descripcion  VARCHAR(80) NOT NULL,
    CONSTRAINT rol_pk PRIMARY KEY ( id_rol ),
    CONSTRAINT descripcion_uk UNIQUE ( descripcion )
)

-- Creo la tabla Persona
CREATE TABLE persona (
    id_persona  NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    documento   VARCHAR(30) NOT NULL,
    apellido1   VARCHAR(30) NOT NULL,
    apellido2   VARCHAR(30),
    nombre1     VARCHAR(30) NOT NULL,
    nombre2     VARCHAR(30),
    fecha_nac   DATE,
    mail        VARCHAR(50) NOT NULL,
    clave       VARCHAR(50) NOT NULL,
    id_rol      NUMBER NOT NULL,
    CONSTRAINT pk_persona PRIMARY KEY ( id_persona ),
    CONSTRAINT uk_mail UNIQUE ( mail )
)

-- Agrego la FK a Persona de la relacion con ROL
ALTER TABLE persona
    ADD CONSTRAINT fk_persona_rol FOREIGN KEY ( id_rol )
        REFERENCES rol ( id_rol );

-- Agrego la tabla Rol_Funcionalidad
CREATE TABLE rol_funcionalidad (
    id_rol_funcionalidad  NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    id_rol                NUMBER NOT NULL,
    id_funcionalidad      NUMBER NOT NULL,
    CONSTRAINT pk_rol_funcionario PRIMARY KEY ( id_rol_funcionalidad )
);

-- Agrego las FKs en Rol_Funcionalidad
ALTER TABLE rol_funcionalidad
    ADD CONSTRAINT fk_rol_func_rol FOREIGN KEY ( id_rol )
        REFERENCES rol ( id_rol );

ALTER TABLE rol_funcionalidad
    ADD CONSTRAINT fk_rol_func_func FOREIGN KEY ( id_funcionalidad )
        REFERENCES funcionalidad ( id_funcionalidad );