CREATE TABLE emplealdos (
    id_empleado  NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 ),
    cedula       VARCHAR(10) NOT NULL,
    nombre       VARCHAR(50) NOT NULL,
    apellido     VARCHAR(50) NOT NULL,
    PRIMARY KEY ( id_empleado )
);

-- ALTER TABLE empleados RENAME TO empleados;
ALTER TABLE empleados ADD CONSTRAINT uk_empleados_cedula UNIQUE ( cedula );